// src/app/App.tsx
import React from 'react';
import { OpenDocument } from '@/lib/core/Document';
import { Appearance } from '@/lib/core/Appearance';
import { UI } from '@/lib/UI';
import { loadDocument, saveDocument } from '@/features/document-io/documentIO';
import { FormulaBar } from '@/features/formula/FormulaBar';
import { RibbonMenu } from '@/features/ribbon/RibbonMenu';
import { SpreadsheetSurface } from '@/features/sheet/SpreadsheetSurface';
import { AppAction, SheetState } from './types';

const defaultState: SheetState = {isMerged: false, label: 'A1', originalValue: '', value: ''};

export default function App() {
  const [appearance, setAppearance] = React.useState(new Appearance());
  const [fileMode, setFileMode] = React.useState<'file' | 'local'>('file');
  const [sheetState, setSheetState] = React.useState(defaultState);
  const fileModeRef = React.useRef(fileMode);
  const loadRef = React.useRef<((data: string) => void) | null>(null);
  const uiRef = React.useRef<UI | null>(null);

  const onChange = (doc: OpenDocument) => {
    setAppearance(doc.ActiveSheet.SelectedAppearance);
    setSheetState({
      isMerged: uiRef.current ? uiRef.current.isMerged : false,
      label: doc.ActiveSheet.SelectionLabel,
      originalValue: doc.ActiveSheet.SelectedValue || '',
      value: doc.ActiveSheet.SelectedValue || '',
    });
    if (fileModeRef.current === 'local') {
      localStorage.setItem('data', JSON.stringify(doc.save()));
    }
  };

  const onModeChanged = (mode: 'file' | 'local') => {
    if (fileModeRef.current === 'file' && mode === 'local' && localStorage.getItem('data')) {
      if (loadRef.current) {
        loadRef.current(localStorage.getItem('data') as string);
      }
    }
    fileModeRef.current = mode;
    setFileMode(mode);
  };

  const onAction = (action: AppAction) => {
    if (action.actionName === 'save-ows') {
      return saveDocument(uiRef.current);
    }
    if (action.actionName === 'load-ows') {
      return loadDocument(uiRef.current);
    }
    if (action.actionName === 'formula-template') {
      return setSheetState({...sheetState, value: action.args});
    }
    return uiRef.current && uiRef.current.execCmd(action.actionName, action.args);
  };

  return React.createElement('div', {className: 'ows-app'},
    React.createElement(RibbonMenu, {appearance, fileMode, onAction, onModeChanged, state: sheetState}),
    React.createElement(FormulaBar, {
      label: sheetState.label,
      onAbort: () => setSheetState({...sheetState, value: sheetState.originalValue}),
      onCommit: () => commitFormula(uiRef.current, sheetState),
      onValueChange: (value) => setSheetState({...sheetState, value}),
      value: sheetState.value,
    }),
    React.createElement(SpreadsheetSurface, {
      onChange,
      onReady: (ui) => uiRef.current = ui,
      registerLoad: (load) => loadRef.current = load,
    }),
    React.createElement('footer', {className: 'ows-status-bar'}, 'Ready'),
  );
}

function commitFormula(ui: UI | null, state: SheetState) {
  if (ui && state.value !== state.originalValue) {
    ui.execCmd('change-value', null, null, state.value);
  }
}

// src/App.vue
<script lang="ts">
  import { Component, Vue } from 'vue-property-decorator';
  import RibbonMenu from "@/RibbonMenu.vue"
  import FormulaBar from "@/FormulaBar.vue"
  import OpenSheet from "@/OpenSheet.vue"
  import SheetSelector from "@/SheetSelector.vue"
  import StatusBar from "@/StatusBar.vue"
  import { OpenDocument } from "@/lib/core/Document"
  import { UI } from "@/lib/UI"
  import { Appearance } from "@/lib/core/Appearance"

  @Component({
    components: {
      StatusBar,
      SheetSelector,
      OpenSheet,
      FormulaBar,
      RibbonMenu,
    },
  })
  export default class App extends Vue {
    private uiManager!: UI
    private appearance: Appearance = new Appearance()
    private fileMode: 'local' | 'file' = 'file'
    private state = {
      isMerged: false,
      label: 'A1',
      value: null,
      originalValue: null
    }

    onReady(ui: UI) {
      this.uiManager = ui
    }

    onChange(doc: OpenDocument) {
      this.appearance = doc.ActiveSheet.SelectedAppearance;
      this.state.isMerged = this.uiManager.isMerged
      this.state.label = doc.ActiveSheet.SelectionLabel
      this.state.value = doc.ActiveSheet.SelectedValue
      this.state.originalValue = doc.ActiveSheet.SelectedValue

      if (this.fileMode == 'local') {
        localStorage.setItem('data', JSON.stringify(doc.save()))
      }
    }

    onCommit() {
      if (this.state.value != this.state.originalValue) {
        this.uiManager.execCmd('change-value', null, null, this.state.value);
      }
    }

    onAbort() {
      this.state.value = this.state.originalValue
    }

    onAction({actionName, args}: { actionName: string, args: any }) {
      if (actionName === 'save-ows') {
        this.onSave()
        return
      } else if (actionName === 'load-ows') {
        this.onLoad()
        return
      }
      this.uiManager.execCmd(actionName, args)
    }

    onModeChanged(newMode: 'file' | 'local') {
      if (this.fileMode == 'file') {
        (<any>this.$refs['sheet']).load(localStorage.getItem('data'))
      }
      this.fileMode = newMode;
    }

    onLoad() {
      const win = <any>window;
      const ui = this.uiManager

      if (win.File && win.FileReader && win.FileList && win.Blob) {
        let f = document.createElement('input');
        f.type = 'file';
        f.accept = '.ows';
        f.addEventListener('change', function (evt: any) {
          let file = evt.target['files'][0];
          let reader = new FileReader();
          reader.addEventListener('load', function (loadEvt: any) {
            const rawData = loadEvt.target['result']
            ui.load(rawData);
          });
          reader.readAsText(file, 'utf8');
        });
        f.click();
      } else {
        alert('The File APIs are not fully supported in this browser.');
      }
    }

    onSave() {
      const content = this.uiManager.save();
      const uriContent = "data:application/octet-stream," + encodeURIComponent(content);
      let a = document.createElement("a");
      a['download'] = "document.ows";
      a.href = uriContent;
      a.target = "_blank";
      a.click();
    }

  }
</script>

<template>
    <div id="app">
        <ribbon-menu :appearance="appearance"
                     :state="state"
                     @mode-changed="onModeChanged"
                     @action="onAction"/>
        <formula-bar :label="state.label"
                     v-model="state.value"
                     @commit="onCommit"
                     @abort="onAbort"/>
        <open-sheet ref="sheet" @ready="onReady" @change="onChange"/>
        <status-bar/>
    </div>
</template>

<style lang="scss">

</style>
